# Generated by Django 5.1.5 on 2025-02-03 18:08

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='get_full_name', unique=True),
        ),
    ]
